# Generated by Django 5.2.5 on 2025-08-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_path',
        ),
        migrations.CreateModel(
            name='LessonPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lesson_pdfs/')),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='courses.lesson')),
            ],
        ),
    ]
