# Generated by Django 4.2.23 on 2025-08-16 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_lessonprogress_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='video_progress_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_watched_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessonpdf'),
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('video_path', models.CharField(blank=True, max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('video_format', models.CharField(default='mp4', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Video',
                'verbose_name_plural': 'Lesson Videos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson_pdf')},
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessonvideo'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson_pdf'), ('user', 'lesson_video')},
        ),
    ]
