# Generated by Django 4.2.23 on 2025-08-17 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_lessonprogress_video_progress_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('order', models.IntegerField(default=0, help_text='Order of the question in the lesson')),
                ('points', models.IntegerField(default=1, help_text='Points awarded for correct answer')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'MCQ Question',
                'verbose_name_plural': 'MCQ Questions',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='The answer option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?')),
                ('order', models.IntegerField(default=0, help_text='Order of the option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.mcqquestion')),
            ],
            options={
                'verbose_name': 'MCQ Option',
                'verbose_name_plural': 'MCQ Options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MCQProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('total_points_possible', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False, help_text='All questions attempted')),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCQ Progress',
                'verbose_name_plural': 'MCQ Progress Records',
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='MCQAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1, help_text='Which attempt this is for the user')),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.mcqquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.mcqoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCQ Attempt',
                'verbose_name_plural': 'MCQ Attempts',
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'question', 'attempt_number')},
            },
        ),
    ]
